# Use an official Python runtime as a parent image
FROM python:3.6-alpine as base

COPY src/ /app

WORKDIR /app

RUN pip install -e .

# Run command when the container launches
CMD ["hello", "--help"]
